version: "3.8"
services:
  server:
    container_name: backend
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      - PGHOST=postgres # NAME OF THE SERVICE
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cityweather
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: {}
